package model;
// Generated 21.02.2018 13:40:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private int cityId;
     private String cityName;
     private Set<Pnz> pnzs = new HashSet<Pnz>(0);

    /**
     *
     */
    public City() {
    }
     public City(int cityId) {
         this.cityId=cityId;
    }
    
    /**
     *
     * @param cityName
     */
    public City(String cityName) {
        this.cityName = cityName;
    }
	
    /**
     *
     * @param cityId
     * @param cityName
     */
    public City(int cityId, String cityName) {
        this.cityId = cityId;
        this.cityName = cityName;
    }

    /**
     *
     * @param cityId
     * @param cityName
     * @param pnzs
     */
    public City(int cityId, String cityName, Set<Pnz> pnzs) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.pnzs = pnzs;
    }
   
    /**
     *
     * @return
     */
    public int getCityId() {
        return this.cityId;
    }
    
    /**
     *
     * @param cityId
     */
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }

    /**
     *
     * @return
     */
    public String getCityName() {
        return this.cityName;
    }
    
    /**
     *
     * @param cityName
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     *
     * @return
     */
    public Set<Pnz> getPnzs() {
        return this.pnzs;
    }
    
    /**
     *
     * @param pnzs
     */
    public void setPnzs(Set<Pnz> pnzs) {
        this.pnzs = pnzs;
    }




}


