package model;
// Generated 21.02.2018 13:40:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pnz generated by hbm2java
 */
public class Pnz  implements java.io.Serializable {


     private int pnzId;
     private String pnzName;
     private Set<PnzData> pnzDatas = new HashSet<PnzData>(0);

    public Pnz() {
    }

    public Pnz(String pnzName) {
        this.pnzName = pnzName;
    }
	
    public Pnz(int pnzId, String pnzName) {
        this.pnzId = pnzId;
        this.pnzName = pnzName;
    }
    public Pnz(int pnzId, String pnzName, Set<PnzData> pnzDatas) {
       this.pnzId = pnzId;
       this.pnzName = pnzName;
       this.pnzDatas = pnzDatas;
    }
   
    public int getPnzId() {
        return this.pnzId;
    }
    
    public void setPnzId(int pnzId) {
        this.pnzId = pnzId;
    }
    public String getPnzName() {
        return this.pnzName;
    }
    
    public void setPnzName(String pnzName) {
        this.pnzName = pnzName;
    }
    public Set<PnzData> getPnzDatas() {
        return this.pnzDatas;
    }
    
    public void setPnzDatas(Set<PnzData> pnzDatas) {
        this.pnzDatas = pnzDatas;
    }




}


